# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20171024_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.CharField(max_length=200)),
                ('dynamic', models.CharField(max_length=6)),
                ('type', models.CharField(max_length=7)),
            ],
        ),
    ]
